---
title: "Problem Set 3"
author: "Marc Eskew"
date: "4/22/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(plotly)
```

## Problem 1


```{r problem_1} 

v <- runif(10000)

z <- v^(4/3)
y <- runif(10000)*.75*z^(-.25)

x_sign <- runif(10000)
y_sign <- runif(10000)

z_iden <- ifelse(x_sign < .5, -1,1)
y_iden <- ifelse(y_sign < .5, -1,1)

z_mir <- z*z_iden
y_mir <- y*y_iden

ggplot(data.frame(x=z_mir, y = y_mir),aes(x=z_mir, y = y_mir)) +
  geom_point(size = .5)
```


## Problem 2


```{r problem_2a}
K <- 1
c <- 2

p2_func <- function(K=1,x=0,y=0){
  K*exp(-(x^2)-(y^2) + ((cos(x*y)*x)/2))
}

df <- data.frame()

for(i in seq(1,10000)){
  
  flag <- FALSE
  while(flag == FALSE){
    
    x_iden <- ifelse(runif(1) < .5, -1,1)
    y_iden <- ifelse(runif(1) < .5, -1,1)
    
    x <- -log(1-runif(1))*x_iden
    y <- -log(1-runif(1))*y_iden
    u <- runif(1)
    
    g <- c*exp(-abs(x)-abs(y)+abs(x))
    f <- p2_func(K=K, x = x, y = y)
    
    ug <- u*g
    
    if(ug <= f) {
      df_temp <- data.frame(x = x, y = y,cg = g,u=u,ucg = u*g, f = f)
      df <- bind_rows(df,df_temp)
      break
    } 
  }
}

df1 <- df %>%
  mutate(xy = x*y)

expval <- mean(df1$xy)
expval
```

The estimate of $E(XY)$ is **`r expval`**

```{r problem_2b}
ggplot(df) +
  geom_density2d_filled(aes(x=x,y=y),alpha = 0.75) + 
  theme_minimal() 
```

## Problem 3


```{r problem_3}
df <- data.frame()

while(nrow(df) < 1000) {
  
  sample <- data.frame(x = rnorm(1000,0,1),y = rnorm(1000,0,1),z = rnorm(1000,0,1)) %>%
    mutate(norm = 1/sqrt(x^2+y^2+z^2)) %>%
    transmute(x = x*norm, y = y*norm, z = z*norm) %>%
    mutate(f = exp(2*z), g=exp(2), c=runif(1000),gc = g*c) %>%
    filter(f>=gc)
  
  df <- bind_rows(df,sample)
  
}

sample3 <- df[1:1000,]

dope_sphere <- plot_ly(sample3,x =~x, y=~y, z = ~z, type = "scatter3d",
        mode = "markers",opacity = 1, marker = list(size = 5,color = ~z))

htmlwidgets::saveWidget(widget = dope_sphere, file = "dope_sphere.html")
webshot2::webshot(url = "dope_sphere.html", file = "dope_sphere.png",
                  delay = 1, zoom = 4, vheight = 800)


```

## Problem 4

If $p(k) = \mathbb{P}(X=k) \text{ for }k = 1,2,...$ and $g(k) = \mathbb{P}(Y=k) \text{ for }k = 1,2,...$ we can show that acceptance/rejection is valid for the discrete case.  If $U \sim U(0,1)$ and there exists a $C \in (0,\infty)$ such that:

$$
\begin{aligned}
\max_{k\geq1}\frac{p(k)}{g(k)} \leq C
\end{aligned}
$$
then

$$
\begin{aligned}
0 \leq \frac{1}{C}\frac{p(k)}{g(k)} \leq 1 \text{  for all } k \in (1,\infty)
\end{aligned}
$$

We can further determine that the probability of $U$ is equal to this value.

$$
\begin{aligned}
\mathbb{P}(U \leq \frac{1}{C}\frac{p(k)}{g(k)}) =\frac{1}{C}\frac{p(k)}{g(k)}
\end{aligned}
$$

Using the definition of conditional probability

$$
\begin{aligned}
\mathbb{P} \left (Y = k | U \leq \frac{1}{C}\frac{p(k)}{g(k)}\right) &= \frac{\mathbb{P}(Y=k) \cap \mathbb{P}(U \leq \frac{1}{C}\frac{p(k)}{g(k)})}{\mathbb{P}(U \leq \frac{1}{C}\frac{p(k)}{g(k)})}\\
&= \frac{g(k) \cap \frac{1}{C}\frac{p(k)}{g(k)}}{\frac{1}{C}\frac{p(k)}{g(k)}} \\
&= Cg(k)\frac{1}{C}\frac{p(k)}{g(k)}\\
&= p(k) \\
&= \mathbb{P}(X = k)
\end{aligned}
$$